### ISSUE TITLE
Wire.requestFrom() should not have a beginTransmission or endTransmission.

### ISSUE THREAD

**Issue by Koepel** [sparkfun/SparkFun_HMC6343_Arduino_Library#2]
In three places in SFE_HMC6343.cpp, the Wire.requestFrom() has a Wire.beginTransmission() and Wire.endTransmission(), but the Wire.requestFrom() is a complete I2C transaction on its own.

The Wire.beginTransmission() and Wire.endTransmission() should only used when writing data to a I2C Slave.

**Comment by bboyho** [comment]
`Wire.beginTransmission() ` removed before `Wire.requestFrom()` and `Wire.endTransmission()` removed after `Wire.requestFrom()` in this commit => https://github.com/sparkfun/SparkFun_HMC6343_Arduino_Library/commit/334217ecca4d6c07097c16fc51cad80c2b636925 . I tested the code to verify the [two common mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2).
